### ISSUE TITLE
Add Unity scripting references and links throughout Dice Game

### ISSUE THREAD

**Issue by DerekCresswell** [DerekCresswell/GameDesign11#21]
The entire dice game needs to be linked up to the Unity API, Manual, and C# docs. Only bits of it have currently been added.
For each lesson in the unit find the first mentions of each new term, keyword, function, etc. and link it to a corresponding web page. These should be [C# Docs](https://docs.microsoft.com/en-us/dotnet/csharp/), [Unity Manual](https://docs.unity3d.com/Manual/index.html), or [Unity API](https://docs.unity3d.com/ScriptReference/).

Please go by the specs outlined in the CONTRIBUTING.md file for how to format everything nicely.

**Comment by DerekCresswell** [comment]
This will be assigned to @EricTannant when he joins.  
Here I'll link some good resources for you to get started.  
[Not Github, but amazing git tutorials](https://www.atlassian.com/git/tutorials/learn-git-with-bitbucket-cloud)  
[Githubs tutorials](https://guides.github.com/activities/hello-world/)  
[Awesome interactive git practice](https://learngitbranching.js.org/)   
[Git for Windows](https://gitforwindows.org/)
Make sure to read the CONTRIBUTING.md file as well.

Put any questions you have here and I'll answer them for you.

***And note I'd like you to make a new branch for your changes and not put them directly on master.*** That will be in the tutorials : )

**Comment by EricTannant** [comment]
Ok

**Comment by DerekCresswell** [comment]
Looks like this has been covered over the last few months. Closing.
